### ISSUE TITLE
Doesn't work with Webpack2

### ISSUE THREAD

**Issue by bbottema** [lacolaco/ng2-test-seed#2]
Webpack 2.6.1, Node 6.10.2, npm 5.0.3

```
> npm run build

 ng2-test-seed@1.0.0 build D:\workstation\ng2-test-seed
 webpack

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "./dist" is not an absolute path!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng2-test-seed@1.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng2-test-seed@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Username\AppData\Roaming\npm-cache\_logs\2017-06-08T18_25_03_722Z-debug.log
```

**Comment by bbottema** [comment]
If I switch to an absolute path using `path.resolve(__dirname, './dist')`, the following error occurs next:

```
          Asset     Size  Chunks             Chunk Names
main.bundle.js  6.78 kB       0  [emitted]  main
   [0] ./src/main.ts 573 bytes {0} [built] [failed] [1 error]

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (D:\workstation\ng2-test-seed\node_modules\awesome-typescript-loader\src\instance.ts:266:72)
    at Object.ensureInstance (D:\workstation\ng2-test-seed\node_modules\awesome-typescript-loader\src\instance.ts:145:5)
    at compiler (D:\workstation\ng2-test-seed\node_modules\awesome-typescript-loader\src\index.ts:37:20)
    at Object.loader (D:\workstation\ng2-test-seed\node_modules\awesome-typescript-loader\src\index.ts:18:18)
```
